### ISSUE TITLE
factory_bot 6 checklist

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot#1336]
- [x] Remove Rails 4.2 from test matrix
- [x] Remove EOL ruby versions from test matrix
- [x] Remove Rails 4.2 logic from features/support/factories.rb
- [x] Remove deprecated methods from lib/factory.rb
- [x] Bump FactoryBot::Deprecation to 7.0

**Comment by mvz** [comment]
Will there be a release of factory bot 5 with Ruby 2.7 support?

**Comment by composerinteralia** [comment]
That’s definitely possible. Do you know if there is anything we need to do in particular besides add 2.7 to Travis? Are we getting keyword argument warnings or anything like that?

**Comment by mvz** [comment]
When using FactoryBot, I'm getting some warnings due to the use of `delegate`. It seems this has already been fixed in activesupport: https://github.com/rails/rails/commit/11ac92ef79d5943201d5b47b7a783e510b1e4067

I don't know if these show up in FactoryBot's own tests or not.

**Comment by mvz** [comment]
I checked, and they do show up. They're a bit swamped by warnings in the dependencies, mainly activerecord.

**Comment by composerinteralia** [comment]
We fixed one of the warnings in https://github.com/thoughtbot/factory_bot/commit/7f2a4057b6ed8647506bdc9aa80ea8e2853d8798. I can release a patch version with that fix before version 6 goes out. If there are warnings beyond that we can address them as they come up and release additional patch versions as necessary.

**Comment by carlost** [comment]
@composerinteralia a `5.1` patch release including commit 7f2a405 would be nice.  trying to clean up all of these deprecation warnings :)

**Comment by composerinteralia** [comment]
Done! That had fallen off my radar.

**Comment by carlost** [comment]
@composerinteralia either you rock or I have magic powers.  i am going to go with you rock ... for now.

**Comment by mvz** [comment]
Thanks, @composerinteralia!
